#!/bin/bash
set -e
chmod 755 /usr/local/bin/terminal-love.sh /usr/local/bin/terminal-love-network.sh
exit 0
#!/bin/bash
set -e
chmod 755 /usr/local/bin/terminal-love.sh /usr/local/bin/terminal-love-network.sh
exit 0
